services:
  mysql:
    image: mysql:8
    ports:
      - '${MYSQL_PORT:-3307}:3306'
    environment:
      MYSQL_USER: 'db'
      MYSQL_PASSWORD: 'db@123'
      MYSQL_DATABASE: 'package'
      MYSQL_ROOT_PASSWORD: 'root'
